name = "DevSoc Modpack"
author = "DevSoc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7221983b29301af101fd48b90a6f902c150ecb6c94ecc0ba9dae867ab7bcfde"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
