name = "DevSoc Modpack"
author = "DevSoc"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b5de2422b901bf23ad6138f5168bba2ef69fd7bc75142ecb424627dc4052139"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
